version: '2'

services:
 web:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./src:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  networks:
    - code-network
 php:
  image: sokolby/yii2-php5.6-fpm
  volumes:
    - ./src:/code
  networks:
    - code-network
  environment:
    DB_HOST: database
    DB_PORT: 3306
    DB_USER: root
    DB_PASSWORD: rooot
    DB_NAME: demo_shop
 database:
  image: mysql
  volumes:
    - ./data:/var/lib/mysql
  environment:
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_DATABASE: demo_shop
    MYSQL_ROOT_PASSWORD: rooot
  networks:
    - code-network
 php_my_admin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "12346:80"
  environment:
    PMA_HOST: database
    PMA_PORT: 3306
  networks:
    - code-network
 portainer:
  image: portainer/portainer
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./portainer_data:/data
  ports:
    - "12345:9000"


networks:
 code-network:
  driver: bridge